### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by pitoganzado** [arturleao/samsungtv_custom#3]
Getting this error when run this:
 **python3 get_token.py --ip 192.168.1.199 --port 8080**         
 
Traceback (most recent call last):
  File "get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/usr/share/hassio/homeassistant/custom_components/samsungtv_custom/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/usr/share/hassio/homeassistant/custom_components/samsungtv_custom/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Any help?

**Comment by alamo888PL** [comment]
install module Crypto

**Comment by pitoganzado** [comment]
How can I do it in ubuntu?
"sudo apt-get install python3-crypto" fix the issue :) then 
"sudo apt-get install python3-websocket"

**Comment by pitoganzado** [comment]
Problem solved with:
"sudo apt-get install python3-crypto" and "sudo apt-get install python3-websocket"
